export const BASE_CONFIG = Object.freeze({
  width: 540,
  height: 960,
  fps: 30,
  duration: 10,
  agentCount: 2000,
  maxSpeed: 1.85,
  maxForce: 0.052,
  cohesionWeight: 0.58,
  alignmentWeight: 1.08,
  separationWeight: 1.5,
  neighbourRadius: 25,
  separationRadius: 8,
  interClusterMigrationWeight: 0.48,
  coherenceDensityCount: 6,
  coherenceDensityRadius: 72,
  centrePersistenceLimit: 2.1,
  geographyWeight: 0.3,
  infrastructureWeight: 0.18,
  populationWeight: 0.2,
  continentalWeight: 0.035,
  seaResistance: 0.72,
  seaMovementCost: 1.15,
  trailLength: 8,
  trailOpacity: 0.58,
  densityGlowGain: 0.44,
  glowIntensity: 0.8,
  showStatusLine: true,
  showStatusInCleanMode: false,
  pressureStrength: 2.1,
  pressureRadius: 74,
  pressureStart: 5,
  pressureHoldDuration: 1.25,
  pressureRampIn: 0.65,
  pressureRampOut: 1.05,
  automaticPressure: true,
  thermodynamicAccelerationCost: 1.2,
  thermodynamicDensityCost: 0.35,
  thermodynamicPressureCost: 1.5,
  thermodynamicDecay: 0.982,
  thermodynamicGain: 0.9,
  seed: 1296,
  pressurePresets: {
    southEngland: { centre: [.56,.69], radius: 78, strength: 2.15, rampIn: .65, holdDuration: 1.2, rampOut: 1.05 },
    midlands: { centre: [.53,.59], radius: 76, strength: 2.2, rampIn: .6, holdDuration: 1.25, rampOut: 1.05 },
    northEngland: { centre: [.51,.48], radius: 72, strength: 2.05, rampIn: .65, holdDuration: 1.15, rampOut: 1.0 },
    centralScotland: { centre: [.4,.35], radius: 66, strength: 1.9, rampIn: .7, holdDuration: 1.1, rampOut: 1.0 },
    london: { centre: [.605,.72], radius: 68, strength: 2.35, rampIn: .55, holdDuration: 1.15, rampOut: 1.1 },
  },
});

export const PRESETS = {
  subtle: {},
  dense: { agentCount: 3200, neighbourRadius: 22, coherenceDensityRadius: 62, trailLength: 7, trailOpacity: .5, densityGlowGain: 1.05, glowIntensity: 0.82, separationWeight: 1.48 },
  agitated: { maxSpeed: 2.35, maxForce: 0.075, alignmentWeight: 0.88, separationWeight: 1.65, pressureStrength: 2.6, trailLength: 6 },
  'pressure-test': { pressureStart: 2.5, pressureHoldDuration: 2.2, pressureStrength: 3.1, pressureRadius: 92, thermodynamicPressureCost: 2.2 },
};

export function makeConfig(name = 'subtle') {
  return { ...BASE_CONFIG, ...(PRESETS[name] || PRESETS.subtle), preset: name };
}
